services:
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./conf/nginx.conf:/etc/nginx/conf.d/default.conf:Z
      - certbot-conf:/etc/letsencrypt
      - certbot-www:/var/www/certbot
    depends_on:
      - fhir
    restart: unless-stopped
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"

  certbot:
    image: certbot/certbot
    volumes:
      - certbot-conf:/etc/letsencrypt
      - certbot-www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
    depends_on:
      - nginx

  fhir:
    build: .
    environment:
      - FHIR_ADMIN_USERNAME=${FHIR_ADMIN_USERNAME:-admin}
      - FHIR_ADMIN_PASSWORD=${FHIR_ADMIN_PASSWORD:-admin123}
    ports:
      - "8080:8080"  # Expose FHIR server port for debugging
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped

  db:
    image: postgres:17
    restart: always
    environment:
      POSTGRES_PASSWORD: admin
      POSTGRES_USER: admin
      POSTGRES_DB: hapi
    ports:
      - "5432:5432" # disable this to prevent external access
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./sql/init-postgres.sql:/docker-entrypoint-initdb.d/init-postgres.sql:Z
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d hapi"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  db_data:
  certbot-conf:
  certbot-www:

